package app.gyrolet.mpvrx.exoplayer.core.ui.designsystem

import app.gyrolet.mpvrx.ui.icons.Icons

object NextIcons {
    val Add = Icons.Default.Add
    val Appearance = Icons.Default.Palette
    val ArrowBack = Icons.Default.ArrowBack
    val ArrowDownward = Icons.Default.KeyboardArrowDown
    val ArrowUpward = Icons.Default.KeyboardArrowUp
    val Audio = Icons.Default.Audiotrack
    val Background = Icons.Default.Flip
    val Bold = Icons.Default.FormatBold
    val Brightness = Icons.Default.BrightnessHigh
    val Calendar = Icons.Default.Update // Fallback
    val Caption = Icons.Default.Subtitles
    val Check = Icons.Default.Check
    val CheckBox = Icons.Default.Check // Fallback
    val CheckBoxOutline = Icons.Default.AddCircle // Fallback
    val DarkMode = Icons.Default.Brightness6
    val DashBoard = Icons.Default.GridView
    val Decoder = Icons.Default.DeveloperBoard
    val Delete = Icons.Default.Delete
    val DoubleTap = Icons.Default.FastForward // Fallback
    val Edit = Icons.Default.Edit
    val ExpandMore = Icons.Default.ExpandMore
    val Fast = Icons.Default.FastForward
    val FileOpen = Icons.Default.Folder // Fallback
    val Focus = Icons.Default.AspectRatio // Fallback
    val Folder = Icons.Default.Folder
    val FolderOff = Icons.Default.Folder // Fallback
    val Font = Icons.Default.FormatSize // Fallback
    val FontSize = Icons.Default.FormatSize
    val Headset = Icons.Default.Headset
    val HeadsetOff = Icons.Default.Headset // Fallback
    val Info = Icons.Default.Add // Fallback
    val Language = Icons.Default.Language
    val Length = Icons.Default.AspectRatio // Fallback
    val Link = Icons.Default.Link
    val Location = Icons.Default.SdCard // Fallback
    val Movie = Icons.Default.Movie
    val Pip = Icons.Default.PictureInPictureAlt
    val Pinch = Icons.Default.Add // Fallback
    val Pause = Icons.Default.Pause
    val Play = Icons.Default.PlayArrow
    val Player = Icons.Default.PlayCircle
    val Priority = Icons.Default.NewReleases // Fallback
    val PlaylistPlay = Icons.Default.PlayArrow // Fallback
    val Remove = Icons.Default.Remove
    val Replay = Icons.Default.Refresh // Fallback
    val Resume = Icons.Default.Add // Fallback
    val Rotation = Icons.Default.ScreenRotation
    val Search = Icons.Default.Search
    val Selection = Icons.Default.Add // Fallback
    val Settings = Icons.Outlined.Settings // Available in Outlined
    val Share = Icons.Default.Share
    val SkipNext = Icons.Default.SkipNext
    val SkipPrevious = Icons.Default.SkipPrevious
    val SmartButton = Icons.Default.AutoAwesome // Fallback
    val Style = Icons.Default.Palette // Fallback
    val Subtitle = Icons.Default.Subtitles
    val Size = Icons.Default.AspectRatio // Fallback
    val Sensitivity = Icons.Default.Tune
    val Speed = Icons.Default.Speed
    val SwipeHorizontal = Icons.Default.Add // Fallback
    val SwipeVertical = Icons.Default.Add // Fallback
    val Tap = Icons.Default.Add // Fallback
    val Timer = Icons.Default.Add // Fallback
    val Title = Icons.Default.Add // Fallback
    val Update = Icons.Default.Update
    val Video = Icons.Default.Movie
    val VolumeUp = Icons.Default.VolumeUp
    val ButtonsPosition = Icons.Default.GridView // Fallback
    val Cloud = Icons.Default.CloudDownload // Fallback
    val Close = Icons.Default.Close
    val History = Icons.Default.History
    val DragHandle = Icons.Default.DragHandle
    val Pan = Icons.Default.Add // Fallback
    val HideSource = Icons.Filled.Block
    val SelectAll = Icons.Default.Add // Fallback
    val DeselectAll = Icons.Default.RemoveCircle
    val FastForward = Icons.Default.FastForward
    val BugReport = Icons.Outlined.BugReport // Available in Outlined
    val Copy = Icons.Default.ContentCopy
    val ExtraSettings = Icons.Default.MoreVert // Fallback
    val DeleteSweep = Icons.Default.Delete // Fallback
    val Image = Icons.Default.CameraAlt // Fallback
    val Frame = Icons.Default.FitScreen // Fallback
    val Menu = Icons.Default.MoreVert // Fallback
    val Lock = Icons.Filled.Lock // Available in Filled
    val Loop = Icons.Filled.Repeat // Available in Filled
    val LoopOne = Icons.Filled.RepeatOne
    val LoopAll = Icons.Filled.RepeatOn
    val Shuffle = Icons.Default.Shuffle
    val ShuffleOn = Icons.Default.ShuffleOn
    val Screenshot = Icons.Default.Screenshot
}
